apiVersion: v1
kind: Service
metadata:
  name: heidi-next-site
  namespace: heidi
spec:
  selector:
    app: heidi-next-site
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP

